vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", "<CMD>Oil<CR>")
vim.keymap.set("x", "<leader>p", [["_dP]])
vim.keymap.set({ "i" }, "<C-a>", "<cmd>w<cr><esc>")
vim.keymap.set({ "n" }, "<C-a>", "<cmd>w<cr><esc>")
vim.keymap.set({ "i", "x", "n", "s" }, "<C-q>", "<cmd>q<cr><esc>")
vim.keymap.set({ "n", "i" }, "<C-q>!", "<cmd>q!<cr><esc>")
vim.keymap.set("i", "<C-c>", "<esc>")
vim.keymap.set("", "<leader>nts", "<cmd>Mplayer nts_1<cr>")
vim.keymap.set("", "<leader>2nts", "<cmd>Mplayer nts_2<cr>")
vim.keymap.set("", "<leader>mp", "<cmd>PauseMplayer<cr>")
vim.keymap.set("", "<leader>kmp", "<cmd>KillMplayer<cr>")
vim.keymap.set("", "<leader>info", "<cmd>InfosNts<cr>")
